<?php
require_once dirname(__FILE__).'/../../../../mouf/Mouf.php';

// Let's define the ROOT_URL constant
define('ROOT_URL', base_path());
define('MOUF_URL', ROOT_URL.'vendor/mouf/mouf/');

function druplash_permission() {
	return Mouf::getDruplash()->getPermissions();
}

/**
 * This is the login hook for druplash.
 * Add Mouf information in user SESSION.
 * 
 */
function druplash_user_login($edit, $account) {
	Mouf::getDruplash()->onUserLogin($edit, $account);
}

/**
 * This is the logout hook for druplash.
 * Remove Mouf information in user SESSION.
 * 
 */
function druplash_user_logout($account) {
	Mouf::getDruplash()->onUserLogout($account);
}

/**
 * This is the central hook for druplash.
 * It acts as the controller by binding the paths to the controllers actions.
 * 
 */
function druplash_menu() {
	// Let's find the Drupal Controllers.
	return Mouf::getDruplash()->getDrupalMenus();
}

function druplash_execute_action($actions) {
	return Mouf::getDruplash()->executeAction($actions);
}

/**
 * The hook called to dynamically add blocks to Drupal.
 */
function druplash_block_info() {
	return Mouf::getDruplash()->getDrupalBlocks();
}

/**
 * The hook called to dynamically get the content of a block.
 */
function druplash_block_view($delta = '') {
	return Mouf::getDruplash()->getDrupalBlock($delta);
}
?>