<?php
require_once dirname(__FILE__).'/../../../../mouf/Mouf.php';

use Mouf\Integration\Drupal\Druplash\Druplash;

// Let's define the ROOT_URL constant
define('ROOT_URL', base_path());
define('MOUF_URL', ROOT_URL.'vendor/mouf/mouf/');

function druplash_permission() {
	return Druplash::getPermissions();
}

/**
 * This is the login hook for druplash.
 * Add Mouf information in user SESSION.
 * 
 */
function druplash_user_login($edit, $account) {
	Druplash::onUserLogin($edit, $account);
}

/**
 * This is the logout hook for druplash.
 * Remove Mouf information in user SESSION.
 * 
 */
function druplash_user_logout($account) {
	Druplash::onUserLogout($account);
}

/**
 * This is the central hook for druplash.
 * It acts as the controller by binding the paths to the controllers actions.
 * 
 */
function druplash_menu() {
	// Let's find the Drupal Controllers.
	return Druplash::getDrupalMenus();
}

function druplash_execute_action($actions) {
	return Druplash::executeAction($actions);
}

/**
 * The hook called to dynamically add blocks to Drupal.
 * 
 * @param $op
 * @param $delta
 * @param $edit
 */
function druplash_block($op = 'list', $delta = 0, $edit = array()) {
	if ($op == 'list') {
		return Druplash::getDrupalBlocks();
	} elseif ($op == 'configure') {
		// Do nothing
	} elseif ($op == 'save') {
		// Do nothing
	} elseif ($op == 'view') {
		return Druplash::getDrupalBlock($delta);
	}
}

?>